manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com
    - name: badjeff
      url-base: https://github.com
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
      path: pmw3610-driver
  self:
    path: zmk-config
